#!/bin/bash
# start mosquitto docker container
docker compose -f mosquitto/docker-compose.yaml up -d 1>/dev/null 2>&1

# create and activate python virtual enviroment
if [ ! -d venv ]; then
    echo -e "python virtual enviroment not found\nCreating it (might take a while...)"
    (mkdir venv && python3 -m venv ./venv && venv/bin/pip install -r requirements.txt) > /dev/null 2>&1
fi
source venv/bin/activate

# start the app
./app.py
